site_name: B2GD Documentation
site_description: "B2GD documentation pages. Blender to Godot is a plugin provides many helpers to the export/import process of scenes."
site_author: umaruru

theme:
  name: readthedocs
  prev_next_buttons_location: none

markdown_extensions:
  - admonition

extra_css:
  - style.css

nav:
  - Home: index.md
  - install.md
  - usage.md
  - faq.md
